name: Build and Deploy

on:
  push:
    branches:
      - add/vitejs-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Builds app
        run: cd web-vite && yarn install && yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./web-vite/dist
