name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  NODE: 18
  WORKING_DIRECTORY: web-vite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}
          cache: "yarn"
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/yarn.lock

      - name: Install Dependencies
        run: yarn install
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Lint
        run: yarn lint
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Deploy to surge
        run: yarn deploy
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
